export const CONFIG = {
  prism: {
    gridCols: 13,
    gridRows: 9,
    spacing: 0.5,
    cullRate: 0.07,
    heightMin: 0.8,
    heightMax: 6.0,
    colors: ["#C8CCD4", "#C0C4CC", "#DEE1E8", "#ECEEF3"] as readonly string[],
    baseWidth: 0.38,
    widthVariance: 0.06,
    roughness: 0.7,
    metalness: 0.08,
    lightnessJitter: 0.06,
    positionJitter: 0.04,
  },
  ground: {
    color: "#0A0A0E",
    roughness: 0.9,
    size: 20,
  },
  glow: {
    color: "#4A57A8",
    spreadColor: "#313972",
    edgeColor: "#1A1F45",
    intensity: 4.5,
    distance: 15,
    decay: 1.5,
    position: [0, 0.2, 0] as readonly [number, number, number],
    shadowMapSize: 1024,
    shadowBias: -0.001,
  },
  camera: {
    startHeight: 12,
    endHeight: 4,
    calmSpeed: 0.04,
    rushSpeed: 1.2,
  },
  timeline: {
    duration: 9.5,
    accelStart: 7.5,
    rushStart: 8.5,
  },
  particle: {
    count: 4,
    speed: 0.4,
    trailLength: 60,
    colors: ["#E2516A", "#49D8A8", "#3557D6", "#E2516A"] as readonly string[],
    lineWidth: 0.015,
    yRange: [3.8, 5.0] as readonly [number, number],
    xzRange: 2.5,
  },
  floatingCubes: {
    count: 4,
    sizeRange: [0.3, 0.7] as readonly [number, number],
    color: "#FFFFFF",
    roughness: 0.0,
    metalness: 0.0,
    transmission: 0.98,
    ior: 1.3,
    thickness: 0.4,
    clearcoat: 1.0,
    clearcoatRoughness: 0.0,
    specularIntensity: 1.5,
    specularColor: "#FFFFFF",
    attenuationColor: "#FFFFFF",
    attenuationDistance: 1.0,
    iridescence: 0.4,
    iridescenceIOR: 1.3,
    rotationSpeed: [0.1, 0.3] as readonly [number, number],
    bobAmplitude: 0.1,
    bobPeriod: 4.5,
  },
  lighting: {
    directional: {
      intensity: 1.8,
      color: "#FFFFFF",
      position: [3, 12, 3] as readonly [number, number, number],
      shadowMapSize: 2048,
    },
    ambient: {
      intensity: 0.5,
      color: "#8890A8",
    },
  },
  render: {
    dpr: 0.5,
    noiseIntensity: 0.45,
    vignetteOffset: 0.3,
    vignetteDarkness: 0.9,
  },
} as const;
